name: LevellingOverhaul
version: ${project.version}
main: io.github.devvydoo.levellingoverhaul.LevellingOverhaul
api-version: 1.13
commands:
  mob:
    description: Spawns a test mob
    usage: /mob
  stats:
    description: See player stats
    usage: /stats
