name: LevellingOverhaul
version: ${project.version}
main: io.github.devvydoo.levellingoverhaul.LevellingOverhaul
api-version: 1.13
commands:
  mob:
    description: Spawns a test mob
    usage: /mob
  stats:
    description: See player stats
    usage: /stats
  leveldebug:
    description: Used to modify player progression for debug purposes
    usage: /debug < reset | level | tp > [ CONFIRM / < new level > / [x, y, z] ]
