package me.devvy.leveled.items;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public enum Rarity {

    // White
    COMMON("Common", ChatColor.GRAY.toString(), ChatColor.WHITE.toString()),
    // Green
    UNCOMMON("Uncommon", ChatColor.DARK_GREEN.toString(), ChatColor.GREEN.toString()),
    // Blue
    RARE("Rare", ChatColor.BLUE.toString(), ChatColor.AQUA.toString()),
    // Purple
    ENCHANTED("Enchanted", ChatColor.DARK_PURPLE.toString(), ChatColor.LIGHT_PURPLE.toString()),
    // Gold
    LEGENDARY("Legendary", ChatColor.GOLD.toString() + ChatColor.BOLD, ChatColor.YELLOW.toString());

    public final String RARITY_TITLE;
    public final String LEVEL_LABEL_COLOR;
    public final String NAME_LABEL_COLOR;

    Rarity(String title, String levelColor, String nameColor){
        this.RARITY_TITLE = title;
        this.LEVEL_LABEL_COLOR = levelColor;
        this.NAME_LABEL_COLOR = nameColor;
    }

    public static Rarity getItemRarity(ItemStack itemStack){

        if (itemStack == null) {return null;}

        // Custom item overrides


        // Legendary overrides
        if (itemStack.getType() == Material.ELYTRA)
            return LEGENDARY;

        // Enchanted overrides
        if (itemStack.getEnchantments().size() > 0)
            return ENCHANTED;

        return switch (itemStack.getType()) {
            case ELYTRA, TRIDENT, DRAGON_HEAD, ZOMBIE_HEAD, CREEPER_HEAD, PLAYER_HEAD, HEART_OF_THE_SEA, NETHER_STAR, TOTEM_OF_UNDYING, DRAGON_EGG, WITHER_SKELETON_SKULL, SKELETON_SKULL, BEACON, CONDUIT, NETHERITE_AXE, NETHERITE_BOOTS, NETHERITE_BLOCK, NETHERITE_CHESTPLATE, NETHERITE_HELMET, NETHERITE_HOE, NETHERITE_INGOT, NETHERITE_LEGGINGS, NETHERITE_PICKAXE, NETHERITE_SCRAP, NETHERITE_SHOVEL, NETHERITE_SWORD -> LEGENDARY;
            case ENCHANTED_GOLDEN_APPLE, SHULKER_BOX, BLACK_SHULKER_BOX, BLUE_SHULKER_BOX, BROWN_SHULKER_BOX, CYAN_SHULKER_BOX, GRAY_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX, LIME_SHULKER_BOX, GREEN_SHULKER_BOX, MAGENTA_SHULKER_BOX, ORANGE_SHULKER_BOX, PINK_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, PURPLE_SHULKER_BOX, RED_SHULKER_BOX, WHITE_SHULKER_BOX, YELLOW_SHULKER_BOX, DRAGON_BREATH -> ENCHANTED;
            case DIAMOND_PICKAXE, DIAMOND_SWORD, DIAMOND_BOOTS, DIAMOND_CHESTPLATE, DIAMOND_HELMET, DIAMOND_LEGGINGS, DIAMOND_AXE, DIAMOND_HOE, DIAMOND_SHOVEL, DIAMOND_ORE, DIAMOND_BLOCK, DIAMOND, DIAMOND_HORSE_ARMOR, GOLDEN_APPLE, ENDER_CHEST, POTION, LINGERING_POTION, SPLASH_POTION, OBSIDIAN, END_CRYSTAL, NAME_TAG, ENDER_EYE, ENDER_PEARL, ENCHANTING_TABLE, EMERALD, EMERALD_ORE, EMERALD_BLOCK, DEEPSLATE_EMERALD_ORE, DEEPSLATE_DIAMOND_ORE -> RARE;
            case IRON_PICKAXE, IRON_SWORD, IRON_BOOTS, IRON_CHESTPLATE, IRON_HELMET, IRON_LEGGINGS, IRON_AXE, IRON_HOE, IRON_SHOVEL, IRON_ORE, IRON_BLOCK, IRON_INGOT, IRON_HORSE_ARMOR, GOLDEN_PICKAXE, GOLDEN_SWORD, GOLDEN_BOOTS, GOLDEN_CHESTPLATE, GOLDEN_HELMET, GOLDEN_LEGGINGS, GOLDEN_AXE, GOLDEN_HOE, GOLDEN_SHOVEL, GOLD_ORE, GOLD_BLOCK, GOLD_INGOT, GOLDEN_HORSE_ARMOR, GHAST_TEAR, BLAZE_ROD, BOW, CROSSBOW, SHIELD, COAL, COAL_BLOCK, COAL_ORE, IRON_NUGGET, GOLD_NUGGET, LAPIS_LAZULI, LAPIS_ORE, LAPIS_BLOCK, REDSTONE, REDSTONE_ORE, REDSTONE_BLOCK, COPPER_ORE, GLOWSTONE, GLOWSTONE_DUST, NETHER_QUARTZ_ORE, NETHER_WART, NETHER_WART_BLOCK, QUARTZ, QUARTZ_BLOCK, GRINDSTONE, ANVIL, CHIPPED_ANVIL, DAMAGED_ANVIL, AMETHYST_BLOCK, AMETHYST_CLUSTER, AMETHYST_SHARD, IRON_BARS, RAW_IRON, RAW_IRON_BLOCK, DEEPSLATE_IRON_ORE, NETHER_GOLD_ORE, DEEPSLATE_COAL_ORE, DEEPSLATE_COPPER_ORE, DEEPSLATE_GOLD_ORE, DEEPSLATE_LAPIS_ORE, DEEPSLATE_REDSTONE_ORE, COPPER_BLOCK, COPPER_INGOT, RAW_COPPER -> UNCOMMON;
            default -> COMMON;
        };

    }

}
